site_name: My Docs
## Repository
repo_name: Test
repo_url: 
edit_uri:  #disables edit button
docs_dir: docs

theme:
  name: material
  custom_dir: docs/overrides

extra:
  version:
    provider: mike
    default: latest

plugins:
  - search